name: Temporary Netlify publish

on:
  push:
    branches: [deploy-package]

permissions:
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: lts/*
      - name: Publish current site folder
        working-directory: site
        run: npx -y @netlify/mcp@latest --site-id e82edb32-51fb-421e-9092-54cd06dd0956 --proxy-path "https://netlify-mcp.netlify.app/proxy/eyJhbGciOiJkaXIiLCJlbmMiOiJBMjU2R0NNIn0..hAtJiXYb0kgLLkFS.kg79QqWMuCiu_zu8MH6n9GeNXymaE8N7Fe9gzibGwSdxaHAQ3_QehoLg7Z7P_Cp7nL-zKu5qoNHmm8q1rooUpfmVnBMBavcqeDo5-SXFBbdoZw5qjbn28UkEPg9-2Vun1L10YhNchSh2_hmKQS5gvPuGx_nnflyEVCRLg2KpxEJqTwxNSvMyfl7eQX0GP0Y1g4xi9njJc68GeW59IhcB_oz6N6exfEwQxyCC-3CVxNs5VTWXJiDdIa7GsRQa3gubdYZIuMI-gyHaAczgkqJfOkloS31rPDibVHzOh0nQvNWYZNlTiNWgAFr2g7JviUxcSWfK3QB-0m267gfK1UQGRvl0NSr4eBhmM5s-HAgYtgdJ3mnmTswnhxa6AbuTLDnk9g9XA3Ty.0GIpfXKv4mQByx6rWWSMJg"
